#!/usr/bin/bash
# installs nginx and configure it on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
