#!/usr/bin/env bash
# Script that pings an IP address passes as an argument.

# Accepts argument strings
# Displays Usage: 5-is_the_host_the_network (IP_ADDRESS) if no,
# argument passed.
# Ping the IP 5 timmes.

if [ "$#" -lt "1" ]
then
	echo "Usage: 5-is_the_host_on_the_network { IP_ADDRESS}"
else
	ping "$1" -c 5

fi
