#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school and user ubuntu

# Use SSH with the private key ~/.ssh/school and user ubuntu
ssh -i /root/.ssh/school ubuntu@52.206.218.84
